development:
  adapter: postgresql
  database: madonna_data_base
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: madonna_data_base
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: madonna_data_base
  pool: 5
  timeout: 5000
  